# keybindings
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy -selection clipboard"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind-key -T root C-\\
unbind-key -T copy-mode-vi C-\\

unbind C-b
set-option -g prefix M-o

bind f display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# colors
# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ',xterm-256color:Tc'
# set-option -g status-bg color0
# set-option -g status-fg '#7390AA'
set-option -ga terminal-overrides ",*256col*:RGB"

# appearance
set-option -g status-right ""
set -g pane-border-indicators off

# Status bar
set -g status-position top
set -g status-justify absolute-centre
set -g status-style fg=#EC5B2B,bg=#0c0e13
set -g window-status-current-style "fg=#EE7948,bold"

set -g status-left-length 30
setw -g window-status-format '#I:#(basename "$(dirname "#{pane_current_path}")")/#{b:pane_current_path}#F'
setw -g window-status-current-format '#I:#(basename "$(dirname "#{pane_current_path}")")/#{b:pane_current_path}#F'
# other options
set-option -g renumber-windows on
set-option -g focus-events on
set-option -g history-limit 50000
setw -g monitor-activity off

set -g mouse on
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
